apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-l0i0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-l0i0@sha256:fd3f142594beda518ec60925865a58af24902c01bb3a06c43488ecd5114c63d7
        name: my-nodejs
        resources: {}
status: {}
